### ISSUE TITLE
为什么注入签名之后的app会闪退

### ISSUE THREAD

**Issue by ticsmatic** [gengjf/DingTalkDylib#1]
修改完JFBundleIdentifier的内容后，进行注入（使用的是insert_dylib），重签生成ipa（使用的是ios-app-signer），安装ipa，但是点击ipa就发生闪退为何，求指导

**Comment by gengjf** [comment]
查看系统log，打印的crash日志是什么？请注意生成的dylib的cpu架构，钉钉包含的是armv7和arm64，那么dylib必须也支持这两种。
