### ISSUE TITLE
进了app没找到在哪里设置坐标。。

### ISSUE THREAD

**Issue by AirSars** [gengjf/DingTalkDylib#3]
如题 第一次用钉钉，点了考勤打卡 就急速打卡了。没找到哪边设置坐标啊

**Comment by gengjf** [comment]
重启app之后就可以看到一个绿色的设置按钮，位置设置可以在地图上长按选取设置点，wifi设置可以自己手动填写热点信息，或者在手机连接公司wifi的情况下选择并点击确定即可，其他疑问可以去飘云阁私信我。

**Comment by AirSars** [comment]
找到了。但是只在launch界面出现，到了app自身界面就消失了，我现在自己改到设置界面里去了
