### ISSUE TITLE
HI，有办法hook掉急速打卡这个功能不？

### ISSUE THREAD

**Issue by AirSars** [gengjf/DingTalkDylib#4]
现在因为改了定位，导致每次一进钉钉就自动急速打卡了。。有的时候并不想打卡都自动打了 很是蛋疼，有办法搞一下吗？我能力有限 试了下不行

**Comment by gengjf** [comment]
搞这个没必要吧，极速打卡估计是打开钉钉之后，第一次网络请求时就打了卡，也可以装两个钉钉，一个原版，一个hook过的

**Comment by AirSars** [comment]
好麻烦。刚刚试了下装两个。hook过的提示非官方客户端不让登录。。但是重签的时候如果不改BundleID又不能装两个 咋办

**Comment by gengjf** [comment]
增加个开关，打开app之后，只有在开关开启的状态下才修改位置，关闭时就用你当前的位置
