### ISSUE TITLE
注入动态库闪退 

### ISSUE THREAD

**Issue by taotieming** [gengjf/DingTalkDylib#5]
您好，大神，我目前在注入动态库到钉钉（分享逍客）的时候，会闪退，但是 此动态库在其他 app 注入的时候都是可以正常运行，是否因为钉钉做了防止动态注入的保护 我一直卡顿在这里，不知道您是否有遇见过，如果有的话可否指点小弟一下

**Comment by gengjf** [comment]
没遇到，亲测注入到钉钉、微信、QQ、支付宝、口袋助理都可以成功，这当中有些app做了防注入，需要改下ipa中的执行文件，另外，请用PP助手下载脱壳之后的ipa

**Comment by taotieming** [comment]
嗯嗯 谢谢您的回复，万份感谢，大神，是否有写文章或者资料可以告知如何修改可执行文件来 绕过这个防止动态保护，我找了 一些资料没有找到（目前还在继续寻找），我的ipa包全部是从pp助手上下载的，

**Comment by gengjf** [comment]
把你要注入的ipa和dylib发给我，QQ号：575821914
