### ISSUE TITLE
登录的时候提示我 “param invalid ”

### ISSUE THREAD

**Issue by HolmesZhao** [gengjf/DingTalkDylib#7]
![fb3d7c734d43927f45fa75b0c409f4b6](https://cloud.githubusercontent.com/assets/19728934/24737780/e6d636fe-1ac3-11e7-822d-09eab29d472a.png)

**Comment by HolmesZhao** [comment]
是 bundleID 的问题

**Comment by AemonChan** [comment]
怎么编译的呀
